version: '3.10'

services:
  web:
    container_name: app
    build:
      context: ./app_django
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app_django/:/app/
    ports:
      - "4000:8000"
    env_file:
      - ./.env

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"